// This file was auto-generated by Chameleon
//
// How to use:
//
// 1) You can either compile this code into a shared object
//    that can be loaded by Chameleon's LibAFL components:
//    $ gcc -O3 -flto -march=native -fno-stack-protector -fomit-frame-pointer -fvisibility=hidden -DCHAMELEON_VISIBLE -fPIC -shared -o generator.so <source file>
//
// 2) Or, you can directly integrate this code into one of your projects. See include/baby-chameleon.h for all of the
//    functions you can use.
//
// Quick API overview:
//
// Macros:
//  - CHAMELEON_THREAD_SAFE: Define this to make the code thread-safe
//  - CHAMELEON_VISIBLE: Define this to set visibility to default on chameleon_* functions
//  - CHAMELEON_SEED: The static seed compiled into the code
//
// Functions:
//  - chameleon_seed(): Supply a seed to the internal PRNG
//  - chameleon_generate(): Generate an input according to the grammar rules
//

/***** DEPENDENCIES *****/

#include <stdlib.h>
#include <stdint.h>

/***** MACROS *****/

#undef UNLIKELY
#define UNLIKELY(x) __builtin_expect(!!(x), 0)
#undef LIKELY
#define LIKELY(x) __builtin_expect(!!(x), 1)

#undef THREAD_LOCAL
#ifdef CHAMELEON_THREAD_SAFE
#define THREAD_LOCAL __thread
#else
#define THREAD_LOCAL
#endif

#undef EXPORT_FUNCTION
#ifdef CHAMELEON_VISIBLE
#define EXPORT_FUNCTION __attribute__((visibility ("default")))
#else
#define EXPORT_FUNCTION
#endif

#ifndef CHAMELEON_SEED
 #define CHAMELEON_SEED 1739639165216539016ULL
#endif

/***** PRNG *****/

static THREAD_LOCAL size_t rand_state = CHAMELEON_SEED;

static inline size_t internal_random (void) {
    size_t x = rand_state;
    x ^= x << 13;
    x ^= x >> 7;
    x ^= x << 17;
    return rand_state = x;
}

static const unsigned char WEIGHTED_RAND_LOOKUP_TABLE[] = {
{% for i in 1..=grammar.max_num_of_rules() %}
{%- for j in 0..i -%}
{{ i - 1 }},
{%- endfor %}
{% endfor -%}
};

static size_t weighted_random (size_t num_rules) {
    size_t modulus = (num_rules * (num_rules + 1)) / 2;
    size_t idx = internal_random() % modulus;
    return WEIGHTED_RAND_LOOKUP_TABLE[idx];
}

/***** TERMINALS *****/

{% for (id, content) in grammar.terminals() -%}
static const unsigned char TERMINAL_{{ id }}[{{ content.len() }}] = {
    {% for byte in content -%}
        {{ "{:#02x}" | format(byte) }}
        {%- if !loop.last %},{% endif %}
    {%- endfor %}
};
{% endfor %}

/***** FUNCTIONS *****/

{% for (id, _) in grammar.nonterminals() %}
static size_t _generate_nonterm_{{ id }} (unsigned char*, size_t);
{%- endfor %}

{{ numbersets }}

{{ mutations }}

EXPORT_FUNCTION
void {{ prefix }}_seed (size_t new_seed) {
    rand_state = new_seed;
}

EXPORT_FUNCTION
size_t {{ prefix }}_generate (unsigned char* output, size_t output_length) {
    return _generate_nonterm_{{ grammar.entrypoint().id() }}(output, output_length);
}
