// This file was auto-generated by Chameleon
//
// How to use:
//
// 1) You can either compile this code into a shared object
//    that can be loaded by Chameleon's LibAFL components:
//    $ gcc -O3 -flto -march=native -fno-stack-protector -fomit-frame-pointer -fvisibility=hidden -DCHAMELEON_VISIBLE -fPIC -shared -o generator.so <source file>
//
// 2) Or, you can directly integrate this code into one of your projects. See include/baby-chameleon.h for all of the
//    functions you can use.
//
// Quick API overview:
//
// Macros:
//  - CHAMELEON_THREAD_SAFE: Define this to make the code thread-safe
//  - CHAMELEON_VISIBLE: Define this to set visibility to default on chameleon_* functions
//  - CHAMELEON_SEED: The static seed compiled into the code
//
// Functions:
//  - chameleon_seed(): Supply a seed to the internal PRNG
//  - chameleon_generate(): Generate an input according to the grammar rules
//

{{ head }}

/***** FUNCTIONS *****/

{% for (id, _) in grammar.nonterminals() %}
static size_t _generate_nonterm_{{ id }} (unsigned char*, size_t);
{%- endfor %}

{{ numbersets }}

{{ generators }}

EXPORT_FUNCTION
void {{ prefix }}_seed (size_t new_seed) {
    if (new_seed != 0) {
        rand_state = new_seed;
    } else {
        rand_state = CHAMELEON_SEED;
    }
}

EXPORT_FUNCTION
size_t {{ prefix }}_generate (unsigned char* output, size_t output_length) {
    return _generate_nonterm_{{ grammar.entrypoint().id() }}(output, output_length);
}
