// This file was auto-generated by Chameleon

/***** DEPENDENCIES *****/

#include <stdlib.h>

/***** MACROS *****/

#undef UNLIKELY
#define UNLIKELY(x) __builtin_expect(!!(x), 0)
#undef LIKELY
#define LIKELY(x) __builtin_expect(!!(x), 1)

#undef THREAD_LOCAL
#ifdef CHAMELEON_THREAD_SAFE
#define THREAD_LOCAL __thread
#else
#define THREAD_LOCAL
#endif

#undef EXPORT_FUNCTION
#ifdef CHAMELEON_VISIBLE
#define EXPORT_FUNCTION __attribute__((visibility ("default")))
#else
#define EXPORT_FUNCTION
#endif

#ifndef CHAMELEON_SEED
 #define CHAMELEON_SEED 1739639165216539016ULL
#endif

/***** PRNG *****/

static THREAD_LOCAL size_t rand_state = STATIC_SEED;

static inline size_t random (void) \{
    size_t x = rand_state;
    x ^= x << 13;
    x ^= x >> 7;
    x ^= x << 17;
    return rand_state = x;
\}

EXPORT_FUNCTION
void chameleon_seed (size_t new_seed) \{
    rand_state = new_seed;
\}

/***** TERMINALS *****/

{{- for (idx, content) in terminals -}}
    static const unsigned char TERMINAL_{idx}[{content.len()}] = \{\};
{{- endfor }}
