// This file was auto-generated by Chameleon
//
// How to use:
//
// 1) You can either compile this code into a shared object
//    that can be loaded by Chameleon's LibAFL components:
//    $ gcc -O3 -flto -march=native -fno-stack-protector -fomit-frame-pointer -fvisibility=hidden -DCHAMELEON_VISIBLE -fPIC -shared -o mutator.so <source file>
//
// 2) Or, you can directly integrate this code into one of your projects. See include/chameleon.h for all of the
//    functions you can use.
//
// Quick API overview:
//
// Macros:
//  - CHAMELEON_THREAD_SAFE: Define this to make the code thread-safe
//  - CHAMELEON_VISIBLE: Define this to set visibility to default on chameleon_* functions
//  - CHAMELEON_SEED: The static seed compiled into the code
//  - OMIT_CHAMELEON_MUTATE: Do not include the chameleon_mutate() code
//  - OMIT_CHAMELEON_GENERATE: Do not include the chameleon_generate() code
//  - OMIT_CHAMELEON_SEED: Do not include chameleon_seed()
//  - OMIT_CHAMELEON_INIT: Do not include chameleon_init()
//  - OMIT_CHAMELEON_DESTROY: Do not include chameleon_destroy()
//
// Functions:
//  - chameleon_seed(): Supply a seed to the internal PRNG
//  - chameleon_init(): Initialize a ChameleonWalk
//  - chameleon_destroy(): Deinit a ChameleonWalk
//  - chameleon_mutate(): Given a walk and its associated output, mutate the output according to the grammar rules
//  - chameleon_generate(): Generate a walk and its associated output according to the grammar rules
//

#include <stdlib.h>
#include <stdint.h>

{{ head }}

/***** CODE *****/

#if !defined(OMIT_CHAMELEON_MUTATE) || !defined(OMIT_CHAMELEON_GENERATE)
{% for (id, _) in grammar.nonterminals() %}
static size_t _mutate_nonterm_{{ id }} (step_t*, const size_t, const size_t, size_t*, unsigned char*, size_t);
{%- endfor %}

{{ numbersets }}

{{ mutations }}
#endif /* !defined(OMIT_CHAMELEON_MUTATE) || !defined(OMIT_CHAMELEON_GENERATE) */

#ifndef OMIT_CHAMELEON_SEED
EXPORT_FUNCTION
void {{ prefix }}_seed (size_t new_seed) {
    if (new_seed != 0) {
        rand_state = new_seed;
    } else {
        rand_state = CHAMELEON_SEED;
    }
}
#endif /* OMIT_CHAMELEON_SEED */

#ifndef OMIT_CHAMELEON_INIT
EXPORT_FUNCTION
void {{ prefix }}_init (ChameleonWalk* walk, size_t capacity) {
    walk->steps = malloc(capacity * sizeof(step_t));
    walk->length = 0;
    walk->capacity = capacity;
}
#endif /* OMIT_CHAMELEON_INIT */

#ifndef OMIT_CHAMELEON_DESTROY
EXPORT_FUNCTION
void {{ prefix }}_destroy (ChameleonWalk* walk) {
    free(walk->steps);
    __builtin_memset(walk, 0, sizeof(ChameleonWalk));
}
#endif /* OMIT_CHAMELEON_DESTROY */

#ifndef OMIT_CHAMELEON_MUTATE
EXPORT_FUNCTION
size_t {{ prefix }}_mutate (ChameleonWalk* walk, unsigned char* output, size_t output_length) {
    size_t length = 0;
    if (LIKELY(walk->length > 0)) {
        length = LINEAR_RANDOM(walk->length);
        walk->length = 0;
    }
    return _mutate_nonterm_{{ grammar.entrypoint().id() }}(walk->steps, length, walk->capacity, &walk->length, output, output_length);
}
#endif /* OMIT_CHAMELEON_MUTATE */

#ifndef OMIT_CHAMELEON_GENERATE
EXPORT_FUNCTION
size_t {{ prefix }}_generate (ChameleonWalk* walk, unsigned char* output, size_t output_length) {
    walk->length = 0;
    return _mutate_nonterm_{{ grammar.entrypoint().id() }}(walk->steps, 0, walk->capacity, &walk->length, output, output_length);
}
#endif /* OMIT_CHAMELEON_GENERATE */
